/*If you use BINOPDF, BINOCDF, BINOINV and BINORND, 
please copy and paste "Binom" directory and include this header file like below.*/
/*  #include "./Binom/include.h"    */

#include "BINOCDF.c"
#include "BINOCDF.h"
#include "BINOCDF_data.c"
#include "BINOCDF_data.h"
#include "BINOCDF_initialize.c"
#include "BINOCDF_initialize.h"
#include "BINOCDF_terminate.c"
#include "BINOCDF_terminate.h"
#include "BINOCDF_types.h"
#include "BINOINV.c"
#include "BINOINV.h"
#include "BINOPDF.c"
#include "BINOPDF.h"
#include "BINORND.c"
#include "BINORND.h"
#include "binodeviance.c"
#include "binodeviance.h"
#include "binopdf1.c"
#include "binopdf1.h"
#include "eml_rand.c"
#include "eml_rand.h"
#include "eml_rand_mcg16807_stateful.c"
#include "eml_rand_mcg16807_stateful.h"
#include "eml_rand_mt19937ar_stateful.c"
#include "eml_rand_mt19937ar_stateful.h"
#include "eml_rand_shr3cong_stateful.c"
#include "eml_rand_shr3cong_stateful.h"
#include "gammaln.c"
#include "gammaln.h"
#include "rand.c"
#include "rand.h"
#include "rtGetInf.c"
#include "rtGetInf.h"
#include "rtGetNaN.c"
#include "rtGetNaN.h"
#include "rt_nonfinite.c"
#include "rt_nonfinite.h"
#include "rtwtypes.h"
#include "stirlerr.c"
#include "stirlerr.h"